#!/usr/bin/env bash

ble-color-setface auto_complete fg=238,underline
ble-face -s syntax_error fg=242
bleopt complete_ambiguous=

get_color() { tput setaf "$1"; }

# Can be changed to whatever color number you want (0-15)
COL_LINES="$(get_color 6)"
COL_USER="$(get_color 2)"
COL_HOST="$(get_color 2)"
COL_PATH="$(get_color 12)"
COL_ROOT="$(get_color 1)"
COL_GIT="$(get_color 5)"
COL_RESET="$(tput sgr0)"

# prompt
ble-import contrib/prompt-git
bleopt prompt_rps1="\q{contrib/git-info}"
bleopt prompt_ps1_final=
bleopt prompt_ps1_transient=trim

if [ "$EUID" -eq 0 ]; then
  PS1="\[${COL_LINES}\]┌──\[${COL_ROOT}\]\u@${COL_HOST}\h\[${COL_LINES}\]]─[\[${COL_PATH}\]\w\[${COL_LINES}\]]\n\[${COL_LINES}\]└─\[${COL_PATH}\]# \[${COL_RESET}\]"
else
  PS1="\[${COL_LINES}\]┌──[\[${COL_USER}\]\u@${COL_HOST}\h\[${COL_LINES}\]]─[\[${COL_PATH}\]\w\[${COL_LINES}\]]\n\[${COL_LINES}\]└─\[${COL_PATH}\]\$ \[${COL_RESET}\]"
fi
export PS1

# fzf
ble-import -d integration/fzf-completion
ble-import -d integration/fzf-key-bindings

# everforest
ble-face -s syntax_default    fg=223   # fg (#d3c6aa)

# commands / keywords (green)
ble-face -s syntax_command    fg=108,bold   # #a7c080
ble-face -s command_builtin   fg=108
ble-face -s command_keyword   fg=72         # darker green

# strings (yellow/orange)
ble-face -s syntax_quoted     fg=180        # #dbbc7f
ble-face -s syntax_quotation  fg=180,bold

# variables (aqua)
ble-face -s syntax_varname    fg=109        # #83c092

# comments (gray, soft)
ble-face -s syntax_comment    fg=243        # #7a8478

# errors (red, muted)
ble-face -s syntax_error      fg=203,bold   # #e67e80

# operators / delimiters
ble-face -s syntax_delimiter  fg=246

# expansions (purple-ish)
ble-face -s syntax_param_expansion fg=175   # #d699b6

# escapes
ble-face -s syntax_escape     fg=175

# directories / files (blue-green)
ble-face -s command_directory fg=109,underline
ble-face -s command_file      fg=108
