[character]
error_symbol = "[✖](bold red) "
success_symbol = "[❱](bold blue) "

[directory]
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "

[python]
format = "[$symbol$version - $virtualenv]($style) "
symbol = ".py "
style = "bold blue"

[gcloud]
disabled = true
